import z from 'schemastery';
/** Cordis plugin config — host has no tunables; UI prefs live in browser localStorage. */
export declare const PluginConfig: z<Schemastery.ObjectS<{}>, Schemastery.ObjectT<{}>>;
export declare const SETTINGS_NAMESPACE = "raiden-theme";
export declare const RaidenColorConfigSchema: z<Schemastery.ObjectS<{
    preset: z<"raiden-violet" | "raiden-night" | "raiden-sakura" | "custom", "raiden-violet" | "raiden-night" | "raiden-sakura" | "custom">;
    primary: z<string, string>;
    secondary: z<string, string>;
    accent: z<string, string>;
    background: z<string, string>;
    surface: z<string, string>;
    text: z<string, string>;
    success: z<string, string>;
    warning: z<string, string>;
    error: z<string, string>;
    dynamicEnabled: z<boolean, boolean>;
    dynamicIntensity: z<"low" | "standard" | "high", "low" | "standard" | "high">;
}>, Schemastery.ObjectT<{
    preset: z<"raiden-violet" | "raiden-night" | "raiden-sakura" | "custom", "raiden-violet" | "raiden-night" | "raiden-sakura" | "custom">;
    primary: z<string, string>;
    secondary: z<string, string>;
    accent: z<string, string>;
    background: z<string, string>;
    surface: z<string, string>;
    text: z<string, string>;
    success: z<string, string>;
    warning: z<string, string>;
    error: z<string, string>;
    dynamicEnabled: z<boolean, boolean>;
    dynamicIntensity: z<"low" | "standard" | "high", "low" | "standard" | "high">;
}>>;
export declare const RaidenSettingsSchema: z<Schemastery.ObjectS<{
    schemaVersion: z<number, number>;
    enabled: z<boolean, boolean>;
    displayName: z<string, string>;
    subtitle: z<string, string>;
    avatar: z<string, string>;
    portrait: z<string, string>;
    timePhaseEnabled: z<boolean, boolean>;
    stateColorEnabled: z<boolean, boolean>;
    motion: z<"standard" | "off", "standard" | "off">;
    reducedMotion: z<boolean, boolean>;
    veilOpacity: z<number, number>;
    acrylicPercent: z<number, number>;
    frameOpacity: z<number, number>;
    panelOpacity: z<number, number>;
    characterOpacity: z<number, number>;
    showLeftCharacter: z<boolean, boolean>;
    showRightCharacter: z<boolean, boolean>;
    showMascot: z<boolean, boolean>;
    showWorkspaceMascot: z<boolean, boolean>;
    colors: z<Schemastery.ObjectS<{
        preset: z<"raiden-violet" | "raiden-night" | "raiden-sakura" | "custom", "raiden-violet" | "raiden-night" | "raiden-sakura" | "custom">;
        primary: z<string, string>;
        secondary: z<string, string>;
        accent: z<string, string>;
        background: z<string, string>;
        surface: z<string, string>;
        text: z<string, string>;
        success: z<string, string>;
        warning: z<string, string>;
        error: z<string, string>;
        dynamicEnabled: z<boolean, boolean>;
        dynamicIntensity: z<"low" | "standard" | "high", "low" | "standard" | "high">;
    }>, Schemastery.ObjectT<{
        preset: z<"raiden-violet" | "raiden-night" | "raiden-sakura" | "custom", "raiden-violet" | "raiden-night" | "raiden-sakura" | "custom">;
        primary: z<string, string>;
        secondary: z<string, string>;
        accent: z<string, string>;
        background: z<string, string>;
        surface: z<string, string>;
        text: z<string, string>;
        success: z<string, string>;
        warning: z<string, string>;
        error: z<string, string>;
        dynamicEnabled: z<boolean, boolean>;
        dynamicIntensity: z<"low" | "standard" | "high", "low" | "standard" | "high">;
    }>>;
}>, Schemastery.ObjectT<{
    schemaVersion: z<number, number>;
    enabled: z<boolean, boolean>;
    displayName: z<string, string>;
    subtitle: z<string, string>;
    avatar: z<string, string>;
    portrait: z<string, string>;
    timePhaseEnabled: z<boolean, boolean>;
    stateColorEnabled: z<boolean, boolean>;
    motion: z<"standard" | "off", "standard" | "off">;
    reducedMotion: z<boolean, boolean>;
    veilOpacity: z<number, number>;
    acrylicPercent: z<number, number>;
    frameOpacity: z<number, number>;
    panelOpacity: z<number, number>;
    characterOpacity: z<number, number>;
    showLeftCharacter: z<boolean, boolean>;
    showRightCharacter: z<boolean, boolean>;
    showMascot: z<boolean, boolean>;
    showWorkspaceMascot: z<boolean, boolean>;
    colors: z<Schemastery.ObjectS<{
        preset: z<"raiden-violet" | "raiden-night" | "raiden-sakura" | "custom", "raiden-violet" | "raiden-night" | "raiden-sakura" | "custom">;
        primary: z<string, string>;
        secondary: z<string, string>;
        accent: z<string, string>;
        background: z<string, string>;
        surface: z<string, string>;
        text: z<string, string>;
        success: z<string, string>;
        warning: z<string, string>;
        error: z<string, string>;
        dynamicEnabled: z<boolean, boolean>;
        dynamicIntensity: z<"low" | "standard" | "high", "low" | "standard" | "high">;
    }>, Schemastery.ObjectT<{
        preset: z<"raiden-violet" | "raiden-night" | "raiden-sakura" | "custom", "raiden-violet" | "raiden-night" | "raiden-sakura" | "custom">;
        primary: z<string, string>;
        secondary: z<string, string>;
        accent: z<string, string>;
        background: z<string, string>;
        surface: z<string, string>;
        text: z<string, string>;
        success: z<string, string>;
        warning: z<string, string>;
        error: z<string, string>;
        dynamicEnabled: z<boolean, boolean>;
        dynamicIntensity: z<"low" | "standard" | "high", "low" | "standard" | "high">;
    }>>;
}>>;
export type RaidenColorConfig = ReturnType<typeof RaidenColorConfigSchema>;
export type RaidenSettings = ReturnType<typeof RaidenSettingsSchema>;
export declare function parseRaidenSettings(value: unknown): RaidenSettings;
export declare const DEFAULT_SETTINGS: RaidenSettings;
/** @deprecated Use parseRaidenSettings — kept for older imports/tests. */
export declare const RaidenSettingsSchemaParser: {
    parse: typeof parseRaidenSettings;
};
